instructions = ["""
        CREATE TABLE IF NOT EXISTS "App_historial" (
            "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
            "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            "fecha" date NOT NULL,
            "nombre" varchar(100) NOT NULL,
            "sexo" varchar(20) NULL,
            "edad" varchar(5) NULL,
            "telefono" varchar(15) NULL,
            "ocupacion" varchar(20) NULL,
            "estadoC" varchar(20) NULL,
            "nacimiento" varchar(20) NULL,
            "tabaquismo" varchar(50) NULL,
            "etilismo" varchar(50) NULL,
            "actividad" varchar(50) NULL,
            "accesibilidad" varchar(50) NULL,
            "pasatiempos" varchar(50) NULL,
            "otros" varchar(50) NULL,
            "dbt" varchar(50) NULL,
            "hta" varchar(50) NULL,
            "cancer" varchar(50) NULL,
            "transf" varchar(50) NULL,
            "cpt" varchar(50) NULL,
            "alergia" varchar(50) NULL,
            "enfr" varchar(50) NULL,
            "fx" varchar(50) NULL,
            "cx" varchar(50) NULL,
            "sv" varchar(50) NULL,
            "reflejos" bool NOT NULL,
            "sensibilidad" bool NOT NULL,
            "lenguaje" bool NOT NULL,
            "Notros" varchar(50) NULL,
            "contractura" varchar(50) NULL,
            "libre" bool NOT NULL,
            "claudicante" bool NOT NULL,
            "Mayuda" bool NOT NULL,
            "espastica" bool NOT NULL,
            "ataxica" bool NOT NULL,
            "Motra" varchar(50) NULL,
            "Iindependiente" bool NOT NULL,
            "Iayudas" bool NOT NULL,
            "Isilla" bool NOT NULL,
            "Icamilla" bool NOT NULL,
            "Findependiente" bool NOT NULL,
            "Fayudas" bool NOT NULL,
            "Fsilla" bool NOT NULL,
            "Fcamilla" bool NOT NULL,
            "Dsitio" varchar(50) NULL,
            "irradiacion" varchar(50) NULL,
            "Dinicial" varchar(20) NULL,
            "Dfinal" varchar(20) NULL,
            "Dobservaciones" varchar(500) NULL,
            "antecedentes" varchar(1000) NULL,
            "motivo" varchar(1000) NULL,
            "resumen" varchar(1000) NULL,
            "diagnostico" varchar(1000) NULL,
            "observaciones" varchar(1000) NULL,
            "plan" varchar(1000) NULL,
            "apendices" varchar(2000) NULL
    );
"""]
