instructions = ["""
        CREATE TABLE IF NOT EXISTS "historial" (
            "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
            "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            "datos_fecha" date NOT NULL,
            "datos_nombre" varchar(100) NOT NULL,
            "datos_sexo" varchar(20) NULL,
            "datos_edad" varchar(5) NULL,
            "datos_telefono" varchar(15) NULL,
            "datos_ocupacion" varchar(20) NULL,
            "datos_estado" varchar(20) NULL,
            "datos_nacimiento" varchar(20) NULL,
            "apnp_tabaquismo" varchar(50) NULL,
            "apnp_etilismo" varchar(50) NULL,
            "apnp_actividad" varchar(50) NULL,
            "apnp_accesibilidad" varchar(50) NULL,
            "apnp_pasatiempos" varchar(50) NULL,
            "apnp_otros" varchar(50) NULL,
            "app_dbt" varchar(50) NULL,
            "app_hta" varchar(50) NULL,
            "app_cancer" varchar(50) NULL,
            "app_transf" varchar(50) NULL,
            "app_cpt" varchar(50) NULL,
            "app_alergia" varchar(50) NULL,
            "app_enfr" varchar(50) NULL,
            "app_fx" varchar(50) NULL,
            "app_cx" varchar(50) NULL,
            "app_sv" varchar(50) NULL,
            "neuro_reflejos" bool NULL,
            "neuro_sensibilidad" bool NULL,
            "neuro_lenguaje" bool NULL,
            "neuro_otros" varchar(50) NULL,
            "contractura_sitio" varchar(50) NULL,
            "marcha_libre" bool NULL,
            "marcha_claudicante" bool NULL,
            "marcha_ayuda" bool NULL,
            "marcha_espastica" bool NULL,
            "marcha_ataxica" bool NULL,
            "marcha_otro" varchar(50) NULL,
            "vi_independiente" bool NULL,
            "vi_ayudas" bool NULL,
            "vi_silla" bool NULL,
            "vi_camilla" bool NULL,
            "vf_independiente" bool NULL,
            "vf_ayudas" bool NULL,
            "vf_silla" bool NULL,
            "vf_camilla" bool NULL,
            "dolor_sitio" varchar(50) NULL,
            "dolor_irradiacion" varchar(50) NULL,
            "dolor_inicial" varchar(20) NULL,
            "dolor_final" varchar(20) NULL,
            "dolor_observaciones" varchar(500) NULL,
            "antecedentes" varchar(1000) NULL,
            "motivo" varchar(1000) NULL,
            "resumen" varchar(1000) NULL,
            "diagnostico" varchar(1000) NULL,
            "observaciones" varchar(1000) NULL,
            "plan" varchar(1000) NULL,
            "apendices" varchar(2000) NULL
    );
"""]

migration_instructions = {
    "select":   """
                SELECT "fecha", "nombre", "sexo", "edad", "telefono", 
                "ocupacion", "estadoC", "nacimiento", "tabaquismo", 
                "etilismo", "actividad", "accesibilidad", "pasatiempos", 
                "otros", "dbt", "hta", "cancer", "transf", "cpt", "alergia", 
                "enfr", "fx", "cx", "sv", "reflejos", "sensibilidad", 
                "lenguaje", "Notros", "contractura", "libre", "claudicante", 
                "Mayuda", "espastica", "ataxica", "Motra", "Iindependiente", 
                "Iayudas", "Isilla", "Icamilla", "Findependiente", "Fayudas", 
                "Fsilla", "Fcamilla", "Dsitio", "irradiacion", "Dinicial", 
                "Dfinal", "Dobservaciones", "antecedentes", "motivo", 
                "resumen", "diagnostico", "observaciones", "plan", "apendices" 
                FROM App_historial
                """,
    "insert":   """
                INSERT INTO "historial" ("datos_fecha", "datos_nombre", "datos_sexo", 
                "datos_edad", "datos_telefono", "datos_ocupacion", "datos_estado", 
                "datos_nacimiento", "apnp_tabaquismo", "apnp_etilismo", "apnp_actividad", 
                "apnp_accesibilidad", "apnp_pasatiempos", "apnp_otros", "app_dbt", "app_hta", 
                "app_cancer", "app_transf", "app_cpt", "app_alergia", "app_enfr", "app_fx", 
                "app_cx", "app_sv", "neuro_reflejos", "neuro_sensibilidad", "neuro_lenguaje", 
                "neuro_otros", "contractura_sitio", "marcha_libre", "marcha_claudicante", 
                "marcha_ayuda", "marcha_espastica", "marcha_ataxica", "marcha_otro", 
                "vi_independiente", "vi_ayudas", "vi_silla", "vi_camilla", "vf_independiente", 
                "vf_ayudas", "vf_silla", "vf_camilla", "dolor_sitio", "dolor_irradiacion", 
                "dolor_inicial", "dolor_final", "dolor_observaciones", "antecedentes", "motivo", 
                "resumen", "diagnostico", "observaciones", "plan", "apendices") 
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 
                ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 
                ?, ?, ?, ?)
                """,
    "orden": ["fecha", "nombre", "sexo", "edad", "telefono",
                "ocupacion", "estadoC", "nacimiento", "tabaquismo",
                "etilismo", "actividad", "accesibilidad", "pasatiempos",
                "otros", "dbt", "hta", "cancer", "transf", "cpt", "alergia",
                "enfr", "fx", "cx", "sv", "reflejos", "sensibilidad",
                "lenguaje", "Notros", "contractura", "libre", "claudicante",
                "Mayuda", "espastica", "ataxica", "Motra", "Iindependiente",
                "Iayudas", "Isilla", "Icamilla", "Findependiente", "Fayudas",
                "Fsilla", "Fcamilla", "Dsitio", "irradiacion", "Dinicial",
                "Dfinal", "Dobservaciones", "antecedentes", "motivo",
                "resumen", "diagnostico", "observaciones", "plan", "apendices"]
}
