instructions = ["""
        CREATE TABLE IF NOT EXISTS "historial" (
            "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
            "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            "datos_fecha" date NOT NULL,
            "datos_nombre" varchar(100) NOT NULL,
            "datos_sexo" varchar(20) NULL,
            "datos_edad" varchar(5) NULL,
            "datos_telefono" varchar(15) NULL,
            "datos_ocupacion" varchar(20) NULL,
            "datos_estado" varchar(20) NULL,
            "datos_nacimiento" varchar(20) NULL,
            "apnp_tabaquismo" varchar(50) NULL,
            "apnp_etilismo" varchar(50) NULL,
            "apnp_actividad" varchar(50) NULL,
            "apnp_accesibilidad" varchar(50) NULL,
            "apnp_pasatiempos" varchar(50) NULL,
            "apnp_otros" varchar(50) NULL,
            "app_dbt_check" bool NULL,
            "app_dbt_text" varchar(50) NULL,
            "app_hta_check" bool NULL,
            "app_hta_text" varchar(50) NULL,
            "app_cancer_check" bool NULL,
            "app_cancer_text" varchar(50) NULL,
            "app_transf_check" bool NULL,
            "app_transf_text" varchar(50) NULL,
            "app_cpt_check" bool NULL,
            "app_cpt_text" varchar(50) NULL,
            "app_alergia_check" bool NULL,
            "app_alergia_text" varchar(50) NULL,
            "app_enfr_check" bool NULL,
            "app_enfr_text" varchar(50) NULL,
            "app_fx_check" bool NULL,
            "app_fx_text" varchar(50) NULL,
            "app_cx_check" bool NULL,
            "app_cx_text" varchar(50) NULL,
            "app_sv_check" bool NULL,
            "app_sv_text" varchar(50) NULL,
            "neuro_reflejos_check" bool NULL,
            "neuro_sensibilidad_check" bool NULL,
            "neuro_lenguaje_check" bool NULL,
            "neuro_otros_check" bool NULL,
            "neuro_otros_text" varchar(50) NULL,
            "contractura_sitio" varchar(50) NULL,
            "marcha_libre_check" bool NULL,
            "marcha_claudicante_check" bool NULL,
            "marcha_ayuda_check" bool NULL,
            "marcha_espastica_check" bool NULL,
            "marcha_ataxica_check" bool NULL,
            "marcha_otro_check" bool NULL,
            "marcha_otro_text" varchar(50) NULL,
            "vi_independiente_check" bool NULL,
            "vi_ayuda_check" bool NULL,
            "vi_silla_check" bool NULL,
            "vi_camilla_check" bool NULL,
            "vf_independiente_check" bool NULL,
            "vf_ayuda_check" bool NULL,
            "vf_silla_check" bool NULL,
            "vf_camilla_check" bool NULL,
            "dolor_sitio" varchar(50) NULL,
            "dolor_irradiacion" varchar(50) NULL,
            "dolor_inicial" varchar(20) NULL,
            "dolor_final" varchar(20) NULL,
            "dolor_observaciones" varchar(500) NULL,
            "antecedentes" varchar(1000) NULL,
            "motivo" varchar(1000) NULL,
            "resumen" varchar(1000) NULL,
            "diagnostico" varchar(1000) NULL,
            "observaciones" varchar(1000) NULL,
            "plan" varchar(1000) NULL,
            "apendices" varchar(2000) NULL
    );
"""]

insert_query = '''
                INSERT INTO "historial" ("datos_fecha", "datos_nombre", "datos_sexo", 
                "datos_edad", "datos_telefono", "datos_ocupacion", "datos_estado", 
                "datos_nacimiento", "apnp_tabaquismo", "apnp_etilismo", "apnp_actividad", 
                "apnp_accesibilidad", "apnp_pasatiempos", "apnp_otros", "app_dbt_check", 
                "app_dbt_text", "app_hta_check", "app_hta_text", "app_cancer_check", 
                "app_cancer_text", "app_transf_check", "app_transf_text", 
                "app_cpt_check", "app_cpt_text", "app_alergia_check", "app_alergia_text", 
                "app_enfr_check", "app_enfr_text", "app_fx_check", "app_fx_text", 
                "app_cx_check", "app_cx_text", "app_sv_check", "app_sv_text", 
                "neuro_reflejos_check", "neuro_sensibilidad_check", 
                "neuro_lenguaje_check", "neuro_otros_check", "neuro_otros_text", 
                "contractura_sitio", "marcha_libre_check", "marcha_claudicante_check", 
                "marcha_ayuda_check", "marcha_espastica_check", "marcha_ataxica_check", 
                "marcha_otro_check", "marcha_otro_text", "vi_independiente_check", 
                "vi_ayuda_check", "vi_silla_check", "vi_camilla_check", 
                "vf_independiente_check", "vf_ayuda_check", "vf_silla_check", 
                "vf_camilla_check", "dolor_sitio", "dolor_irradiacion", "dolor_inicial", 
                "dolor_final", "dolor_observaciones", "antecedentes", "motivo", 
                "resumen", "diagnostico", "observaciones", "plan", "apendices") 
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 
                ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 
                ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                '''

update_query = '''
                UPDATE "historial" 
                SET 
                "updated_at" = CURRENT_TIMESTAMP,
                "datos_fecha" = ?,
                "datos_nombre" = ?,
                "datos_sexo" = ?,
                "datos_edad" = ?, 
                "datos_telefono" = ?, 
                "datos_ocupacion" = ?, 
                "datos_estado" = ?, 
                "datos_nacimiento" = ?, 
                "apnp_tabaquismo" = ?, 
                "apnp_etilismo" = ?, 
                "apnp_actividad" = ?, 
                "apnp_accesibilidad" = ?, 
                "apnp_pasatiempos" = ?, 
                "apnp_otros" = ?, 
                "app_dbt_check" = ?, 
                "app_dbt_text" = ?, 
                "app_hta_check" = ?, 
                "app_hta_text" = ?, 
                "app_cancer_check" = ?, 
                "app_cancer_text" = ?, 
                "app_transf_check" = ?, 
                "app_transf_text" = ?, 
                "app_cpt_check" = ?, 
                "app_cpt_text" = ?, 
                "app_alergia_check" = ?, 
                "app_alergia_text" = ?, 
                "app_enfr_check" = ?, 
                "app_enfr_text" = ?, 
                "app_fx_check" = ?, 
                "app_fx_text" = ?, 
                "app_cx_check" = ?, 
                "app_cx_text" = ?, 
                "app_sv_check" = ?, 
                "app_sv_text" = ?, 
                "neuro_reflejos_check" = ?, 
                "neuro_sensibilidad_check" = ?, 
                "neuro_lenguaje_check" = ?, 
                "neuro_otros_check" = ?, 
                "neuro_otros_text" = ?, 
                "contractura_sitio" = ?, 
                "marcha_libre_check" = ?, 
                "marcha_claudicante_check" = ?, 
                "marcha_ayuda_check" = ?, 
                "marcha_espastica_check" = ?, 
                "marcha_ataxica_check" = ?, 
                "marcha_otro_check" = ?, 
                "marcha_otro_text" = ?, 
                "vi_independiente_check" = ?, 
                "vi_ayuda_check" = ?, 
                "vi_silla_check" = ?, 
                "vi_camilla_check" = ?, 
                "vf_independiente_check" = ?, 
                "vf_ayuda_check" = ?, 
                "vf_silla_check" = ?, 
                "vf_camilla_check" = ?, 
                "dolor_sitio" = ?, 
                "dolor_irradiacion" = ?, 
                "dolor_inicial" = ?, 
                "dolor_final" = ?, 
                "dolor_observaciones" = ?, 
                "antecedentes" = ?, 
                "motivo" = ?, 
                "resumen" = ?, 
                "diagnostico" = ?, 
                "observaciones" = ?, 
                "plan" = ?, 
                "apendices" = ?
                WHERE id = ?;
                '''

delete_query = '''
                DELETE FROM historial WHERE id = ?
                '''

columns = ["datos_fecha", "datos_nombre", "datos_sexo",
           "datos_edad", "datos_telefono", "datos_ocupacion", "datos_estado",
           "datos_nacimiento", "apnp_tabaquismo", "apnp_etilismo", "apnp_actividad",
           "apnp_accesibilidad", "apnp_pasatiempos", "apnp_otros", "app_dbt_check",
           "app_dbt_text", "app_hta_check", "app_hta_text", "app_cancer_check",
           "app_cancer_text", "app_transf_check", "app_transf_text",
           "app_cpt_check", "app_cpt_text", "app_alergia_check", "app_alergia_text",
           "app_enfr_check", "app_enfr_text", "app_fx_check", "app_fx_text",
           "app_cx_check", "app_cx_text", "app_sv_check", "app_sv_text",
           "neuro_reflejos_check", "neuro_sensibilidad_check",
           "neuro_lenguaje_check", "neuro_otros_check", "neuro_otros_text",
           "contractura_sitio", "marcha_libre_check", "marcha_claudicante_check",
           "marcha_ayuda_check", "marcha_espastica_check", "marcha_ataxica_check",
           "marcha_otro_check", "marcha_otro_text", "vi_independiente_check",
           "vi_ayuda_check", "vi_silla_check", "vi_camilla_check",
           "vf_independiente_check", "vf_ayuda_check", "vf_silla_check",
           "vf_camilla_check", "dolor_sitio", "dolor_irradiacion", "dolor_inicial",
           "dolor_final", "dolor_observaciones", "antecedentes", "motivo",
           "resumen", "diagnostico", "observaciones", "plan", "apendices"]

migration_instructions = {
    "select":   """
                SELECT "fecha", "nombre", "sexo", "edad", "telefono", 
                "ocupacion", "estadoC", "nacimiento", "tabaquismo", 
                "etilismo", "actividad", "accesibilidad", "pasatiempos", 
                "otros", "dbt", "hta", "cancer", "transf", "cpt", "alergia", 
                "enfr", "fx", "cx", "sv", "reflejos", "sensibilidad", 
                "lenguaje", "Notros", "contractura", "libre", "claudicante", 
                "Mayuda", "espastica", "ataxica", "Motra", "Iindependiente", 
                "Iayudas", "Isilla", "Icamilla", "Findependiente", "Fayudas", 
                "Fsilla", "Fcamilla", "Dsitio", "irradiacion", "Dinicial", 
                "Dfinal", "Dobservaciones", "antecedentes", "motivo", 
                "resumen", "diagnostico", "observaciones", "plan", "apendices" 
                FROM App_historial
                """,
    "insert":   """
                INSERT INTO "historial" ("datos_fecha", "datos_nombre", "datos_sexo", 
                "datos_edad", "datos_telefono", "datos_ocupacion", "datos_estado", 
                "datos_nacimiento", "apnp_tabaquismo", "apnp_etilismo", "apnp_actividad", 
                "apnp_accesibilidad", "apnp_pasatiempos", "apnp_otros", "app_dbt", "app_hta", 
                "app_cancer", "app_transf", "app_cpt", "app_alergia", "app_enfr", "app_fx", 
                "app_cx", "app_sv", "neuro_reflejos", "neuro_sensibilidad", "neuro_lenguaje", 
                "neuro_otros", "contractura_sitio", "marcha_libre", "marcha_claudicante", 
                "marcha_ayuda", "marcha_espastica", "marcha_ataxica", "marcha_otro", 
                "vi_independiente", "vi_ayudas", "vi_silla", "vi_camilla", "vf_independiente", 
                "vf_ayudas", "vf_silla", "vf_camilla", "dolor_sitio", "dolor_irradiacion", 
                "dolor_inicial", "dolor_final", "dolor_observaciones", "antecedentes", "motivo", 
                "resumen", "diagnostico", "observaciones", "plan", "apendices") 
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 
                ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 
                ?, ?, ?, ?)
                """,
    "orden": ["fecha", "nombre", "sexo", "edad", "telefono",
                "ocupacion", "estadoC", "nacimiento", "tabaquismo",
                "etilismo", "actividad", "accesibilidad", "pasatiempos",
                "otros", "dbt", "hta", "cancer", "transf", "cpt", "alergia",
                "enfr", "fx", "cx", "sv", "reflejos", "sensibilidad",
                "lenguaje", "Notros", "contractura", "libre", "claudicante",
                "Mayuda", "espastica", "ataxica", "Motra", "Iindependiente",
                "Iayudas", "Isilla", "Icamilla", "Findependiente", "Fayudas",
                "Fsilla", "Fcamilla", "Dsitio", "irradiacion", "Dinicial",
                "Dfinal", "Dobservaciones", "antecedentes", "motivo",
                "resumen", "diagnostico", "observaciones", "plan", "apendices"]
}
