def migrate_convert(registro):
    registro_nuevo = (
        registro['fecha'],
        registro['nombre'],
        registro['sexo'],
        registro['edad'],
        registro['telefono'],
        registro['ocupacion'],
        registro['estadoC'],
        registro['nacimiento'],
        registro['tabaquismo'],
        registro['etilismo'],
        registro['actividad'],
        registro['accesibilidad'],
        registro['pasatiempos'],
        registro['otros'],
        1 if len(registro['dbt']) else 0,
        registro['dbt'],
        1 if len(registro['hta']) else 0,
        registro['hta'],
        1 if len(registro['cancer']) else 0,
        registro['cancer'],
        1 if len(registro['transf']) else 0,
        registro['transf'],
        1 if len(registro['cpt']) else 0,
        registro['cpt'],
        1 if len(registro['alergia']) else 0,
        registro['alergia'],
        1 if len(registro['enfr']) else 0,
        registro['enfr'],
        1 if len(registro['fx']) else 0,
        registro['fx'],
        1 if len(registro['cx']) else 0,
        registro['cx'],
        1 if len(registro['sv']) else 0,
        registro['sv'],
        registro['reflejos'],
        registro['sensibilidad'],
        registro['lenguaje'],
        1 if len(registro["Notros"]) else 0,
        registro["Notros"],
        registro["contractura"],
        1 if registro["libre"] else 0,
        1 if registro["claudicante"] else 0,
        1 if registro["Mayuda"] else 0,
        1 if registro["espastica"] else 0,
        1 if registro["ataxica"] else 0,
        1 if len(registro["Motra"]) else 0,
        registro["Motra"],
        1 if registro["Iindependiente"] else 0,
        1 if registro["Iayudas"] else 0,
        1 if registro["Isilla"] else 0,
        1 if registro["Icamilla"] else 0,
        1 if registro["Findependiente"] else 0,
        1 if registro["Fayudas"] else 0,
        1 if registro["Fsilla"] else 0,
        1 if registro["Fcamilla"] else 0,
        registro["Dsitio"],
        registro["irradiacion"],
        registro["Dinicial"],
        registro["Dfinal"],
        registro["Dobservaciones"],
        registro["antecedentes"],
        registro["motivo"],
        registro["resumen"],
        registro["diagnostico"],
        registro["observaciones"],
        registro["plan"],
        registro["apendices"]
    )
    return registro_nuevo
